import {
  AnnotationVersion,
  BrowserPayload,
  CvatTask,
  ExportHistoryEntry,
  ImageDetailPayload,
  ExportPreview,
  ImportReviewRow,
  RecentWorkspace,
  WorkspaceOverview,
} from "../types/workspace";

export const sampleRecentWorkspaces: RecentWorkspace[] = [
  {
    id: "factory-defect-v1",
    name: "factory-defect-v1",
    workspacePath: "C:\\Workspaces\\factory-defect-v1",
    healthStatus: "warning",
    lastOpenedAt: "2026-03-31T12:30:00Z",
    available: true,
  },
  {
    id: "retail-products-v2",
    name: "retail-products-v2",
    workspacePath: "D:\\Workspaces\\retail-products-v2",
    healthStatus: "healthy",
    lastOpenedAt: "2026-03-30T09:20:00Z",
    available: true,
  },
];

export const sampleWorkspaceOverview: WorkspaceOverview = {
  id: "factory-defect-v1",
  name: "factory-defect-v1",
  workspacePath: "C:\\Workspaces\\factory-defect-v1",
  healthStatus: "warning",
  sources: [
    {
      id: "source-coco-old",
      name: "coco_old",
      path: "D:\\datasets\\coco_old",
      type: "COCO",
      status: "ready",
      imageCount: 1450,
      categoryCount: 6,
      corruptedImageCount: 0,
      corruptedImagePaths: [],
      lastScanAt: "2026-03-31 10:30",
    },
    {
      id: "source-yolo-batch-2",
      name: "yolo_batch_2",
      path: "D:\\datasets\\yolo_batch_2",
      type: "YOLO",
      status: "warning",
      imageCount: 980,
      categoryCount: 4,
      corruptedImageCount: 2,
      corruptedImagePaths: [
        "D:\\datasets\\yolo_batch_2\\images\\broken_001.jpg",
        "D:\\datasets\\yolo_batch_2\\images\\broken_009.jpg",
      ],
      lastScanAt: "2026-03-31 10:35",
    },
    {
      id: "source-raw-2026-03",
      name: "raw_2026_03",
      path: "D:\\datasets\\raw_2026_03",
      type: "RAW",
      status: "warning",
      imageCount: 620,
      categoryCount: 0,
      corruptedImageCount: 1,
      corruptedImagePaths: [
        "D:\\datasets\\raw_2026_03\\cameraA\\broken_014.jpg",
      ],
      lastScanAt: "2026-03-31 10:40",
    },
  ],
  categories: [
    { id: "cat-screw", name: "screw", imageCount: 1240 },
    { id: "cat-nut", name: "nut", imageCount: 830 },
    { id: "cat-washer", name: "washer", imageCount: 412 },
    { id: "cat-pallet", name: "pallet", imageCount: 207 },
  ],
};

export const sampleImportReviewRows: ImportReviewRow[] = [
  {
    sourceCategoryId: "source-cat-car",
    sourceCategory: "car",
    sourcePath: "D:\\datasets\\coco_old",
    count: 540,
    sourceTotalImageCount: 1450,
    suggestedAction: "same-name candidate",
    targetUnifiedCategory: "car",
    finalAction: "Merge",
  },
  {
    sourceCategoryId: "source-cat-cars",
    sourceCategory: "cars",
    sourcePath: "D:\\datasets\\coco_old",
    count: 112,
    sourceTotalImageCount: 1450,
    suggestedAction: "similar-name",
    targetUnifiedCategory: "car",
    finalAction: "Merge",
  },
  {
    sourceCategoryId: "source-cat-vehicle-car",
    sourceCategory: "vehicle_car",
    sourcePath: "D:\\datasets\\coco_old",
    count: 98,
    sourceTotalImageCount: 1450,
    suggestedAction: "similar-name",
    targetUnifiedCategory: "car",
    finalAction: "Merge",
  },
  {
    sourceCategoryId: "source-cat-background-obj",
    sourceCategory: "background_obj",
    sourcePath: "D:\\datasets\\coco_old",
    count: 31,
    sourceTotalImageCount: 1450,
    suggestedAction: "no match",
    finalAction: "Ignore",
  },
  {
    sourceCategoryId: "source-cat-pallet",
    sourceCategory: "pallet",
    sourcePath: "D:\\datasets\\coco_old",
    count: 207,
    sourceTotalImageCount: 1450,
    suggestedAction: "new",
    targetUnifiedCategory: "pallet",
    finalAction: "Create New",
  },
];

export const sampleBrowserPayload: BrowserPayload = {
  sources: sampleWorkspaceOverview.sources,
  categories: sampleWorkspaceOverview.categories,
  images: [
    {
      id: "img-001",
      filename: "frame_0001.jpg",
      sourceId: "source-coco-old",
      sourceName: "coco_old",
      originalPath: "D:\\datasets\\coco_old\\images\\frame_0001.jpg",
      annotationStatus: "annotated",
      imageHealthStatus: "healthy",
      imageHealthError: null,
      annotationCount: 2,
      maxBoxAreaRatio: 0.118,
      boxSummaries: [
        { categoryName: "screw", areaRatio: 0.057 },
        { categoryName: "nut", areaRatio: 0.118 },
      ],
      categoryIds: ["cat-screw", "cat-nut"],
      categories: ["screw", "nut"],
    },
    {
      id: "img-002",
      filename: "frame_0002.jpg",
      sourceId: "source-yolo-batch-2",
      sourceName: "yolo_batch_2",
      originalPath: "D:\\datasets\\yolo_batch_2\\images\\frame_0002.jpg",
      annotationStatus: "annotated",
      imageHealthStatus: "healthy",
      imageHealthError: null,
      annotationCount: 1,
      maxBoxAreaRatio: 0.084,
      boxSummaries: [
        { categoryName: "screw", areaRatio: 0.084 },
      ],
      categoryIds: ["cat-screw"],
      categories: ["screw"],
    },
    {
      id: "img-003",
      filename: "frame_0003.jpg",
      sourceId: "source-raw-2026-03",
      sourceName: "raw_2026_03",
      originalPath: "D:\\datasets\\raw_2026_03\\cameraA\\frame_0003.jpg",
      annotationStatus: "unannotated",
      imageHealthStatus: "healthy",
      imageHealthError: null,
      annotationCount: 0,
      maxBoxAreaRatio: null,
      boxSummaries: [],
      categoryIds: [],
      categories: [],
    },
    {
      id: "img-004",
      filename: "frame_0004.jpg",
      sourceId: "source-coco-old",
      sourceName: "coco_old",
      originalPath: "D:\\datasets\\coco_old\\images\\frame_0004.jpg",
      annotationStatus: "annotated",
      imageHealthStatus: "healthy",
      imageHealthError: null,
      annotationCount: 1,
      maxBoxAreaRatio: 0.241,
      boxSummaries: [
        { categoryName: "pallet", areaRatio: 0.241 },
      ],
      categoryIds: ["cat-pallet"],
      categories: ["pallet"],
    },
    {
      id: "img-005",
      filename: "frame_0005.jpg",
      sourceId: "source-yolo-batch-2",
      sourceName: "yolo_batch_2",
      originalPath: "D:\\datasets\\yolo_batch_2\\images\\frame_0005.jpg",
      annotationStatus: "unannotated",
      imageHealthStatus: "healthy",
      imageHealthError: null,
      annotationCount: 0,
      maxBoxAreaRatio: null,
      boxSummaries: [],
      categoryIds: [],
      categories: [],
    },
    {
      id: "img-006",
      filename: "frame_0006.jpg",
      sourceId: "source-coco-old",
      sourceName: "coco_old",
      originalPath: "D:\\datasets\\coco_old\\images\\frame_0006.jpg",
      annotationStatus: "annotated",
      imageHealthStatus: "healthy",
      imageHealthError: null,
      annotationCount: 1,
      maxBoxAreaRatio: 0.036,
      boxSummaries: [
        { categoryName: "washer", areaRatio: 0.036 },
      ],
      categoryIds: ["cat-washer"],
      categories: ["washer"],
    },
  ],
};

export const sampleImageDetailPayload: ImageDetailPayload = {
  id: "img-001",
  filename: "frame_0001.jpg",
  sourceId: "source-coco-old",
  sourceName: "coco_old",
  originalPath: "D:\\datasets\\coco_old\\images\\frame_0001.jpg",
  annotationStatus: "annotated",
  imageHealthStatus: "healthy",
  imageHealthError: null,
  categories: ["screw", "nut"],
  width: 1280,
  height: 720,
  boxes: [
    {
      id: "box-001",
      categoryName: "screw",
      annotationFormat: "coco",
      bboxX: 180,
      bboxY: 140,
      bboxWidth: 240,
      bboxHeight: 220,
    },
    {
      id: "box-002",
      categoryName: "nut",
      annotationFormat: "coco",
      bboxX: 700,
      bboxY: 260,
      bboxWidth: 180,
      bboxHeight: 160,
    },
  ],
};

export const sampleCvatTasks: CvatTask[] = [
  {
    id: "cvat-task-001",
    name: "raw_2026_03_batch_01",
    imageCount: 120,
    status: "In Progress",
    projectName: "defect_v1",
    lastSyncAt: null,
    tempFolder: null,
  },
  {
    id: "cvat-task-002",
    name: "raw_2026_03_batch_02",
    imageCount: 80,
    status: "Ready Sync",
    projectName: "defect_v1",
    lastSyncAt: "2026-03-31 11:10",
    tempFolder: null,
  },
];

export const sampleAnnotationVersions: AnnotationVersion[] = [
  {
    id: "version-3",
    label: "v3",
    createdAt: "2026-03-31 11:25",
    sourceTask: "raw_2026_03_batch_02",
    imageCount: 80,
    boxCount: 412,
    notes: "sync from CVAT",
  },
  {
    id: "version-2",
    label: "v2",
    createdAt: "2026-03-31 10:55",
    sourceTask: "raw_2026_03_batch_01",
    imageCount: 120,
    boxCount: 618,
    notes: "sync from CVAT",
  },
  {
    id: "version-1",
    label: "v1",
    createdAt: "2026-03-31 10:20",
    sourceTask: "initial imported labels",
    imageCount: 2430,
    boxCount: 9184,
    notes: "initial normalized import",
  },
];

export const sampleExportHistory: ExportHistoryEntry[] = [
  {
    id: "export-1",
    outputFormat: "COCO",
    outputPath: "D:\\exports\\factory-defect-v1-coco-v2",
    createdAt: "2026-04-01T11:30:00Z",
    status: "completed",
    exportedImages: 1749,
    exportedBoxes: 14034,
  },
  {
    id: "export-2",
    outputFormat: "YOLO",
    outputPath: "D:\\exports\\factory-defect-v1-yolo",
    createdAt: "2026-04-01T11:42:00Z",
    status: "completed",
    exportedImages: 1749,
    exportedBoxes: 14034,
  },
];

export const sampleExportPreview: ExportPreview = {
  categoryCount: 3,
  includedImages: 1984,
  excludedImages: 231,
  includedBoxes: 8451,
  filenameConflicts: 4,
  conflictDetails: [
    {
      fileName: "0001.jpg",
      items: [
        {
          imageId: "img-1",
          sourceId: "source-a",
          originalPath: "D:\\datasets\\set-a\\0001.jpg",
        },
        {
          imageId: "img-2",
          sourceId: "source-b",
          originalPath: "D:\\datasets\\set-b\\0001.jpg",
        },
      ],
    },
  ],
  splitCounts: {
    train: 1388,
    valid: 298,
    test: 298,
  },
  outputPath: "D:\\exports\\factory-defect-v1-coco",
};
