import {
  AnnotationVersion,
  BrowserPayload,
  CvatTask,
  DatasetMapPayload,
  ExportHistoryEntry,
  ImageDetailPayload,
  ExportPreview,
  ImportReviewRow,
  RecentWorkspace,
  WorkspaceOverview,
} from "../types/workspace";

export const sampleRecentWorkspaces: RecentWorkspace[] = [
  {
    id: "factory-defect-v1",
    name: "factory-defect-v1",
    workspacePath: "C:\\Workspaces\\factory-defect-v1",
    healthStatus: "warning",
    lastOpenedAt: "2026-03-31T12:30:00Z",
    available: true,
  },
  {
    id: "retail-products-v2",
    name: "retail-products-v2",
    workspacePath: "D:\\Workspaces\\retail-products-v2",
    healthStatus: "healthy",
    lastOpenedAt: "2026-03-30T09:20:00Z",
    available: true,
  },
];

export const sampleWorkspaceOverview: WorkspaceOverview = {
  id: "factory-defect-v1",
  name: "factory-defect-v1",
  workspacePath: "C:\\Workspaces\\factory-defect-v1",
  healthStatus: "warning",
  sources: [
    {
      id: "source-coco-old",
      name: "coco_old",
      path: "D:\\datasets\\coco_old",
      type: "COCO",
      status: "ready",
      imageCount: 1450,
      categoryCount: 6,
      corruptedImageCount: 0,
      corruptedImagePaths: [],
      lastScanAt: "2026-03-31 10:30",
    },
    {
      id: "source-yolo-batch-2",
      name: "yolo_batch_2",
      path: "D:\\datasets\\yolo_batch_2",
      type: "YOLO",
      status: "warning",
      imageCount: 980,
      categoryCount: 4,
      corruptedImageCount: 2,
      corruptedImagePaths: [
        "D:\\datasets\\yolo_batch_2\\images\\broken_001.jpg",
        "D:\\datasets\\yolo_batch_2\\images\\broken_009.jpg",
      ],
      lastScanAt: "2026-03-31 10:35",
    },
    {
      id: "source-raw-2026-03",
      name: "raw_2026_03",
      path: "D:\\datasets\\raw_2026_03",
      type: "RAW",
      status: "warning",
      imageCount: 620,
      categoryCount: 0,
      corruptedImageCount: 1,
      corruptedImagePaths: [
        "D:\\datasets\\raw_2026_03\\cameraA\\broken_014.jpg",
      ],
      lastScanAt: "2026-03-31 10:40",
    },
  ],
  categories: [
    { id: "cat-screw", name: "screw", imageCount: 1240 },
    { id: "cat-nut", name: "nut", imageCount: 830 },
    { id: "cat-washer", name: "washer", imageCount: 412 },
    { id: "cat-pallet", name: "pallet", imageCount: 207 },
  ],
};

export const sampleImportReviewRows: ImportReviewRow[] = [
  {
    sourceCategoryId: "source-cat-car",
    sourceCategory: "car",
    sourcePath: "D:\\datasets\\coco_old",
    count: 540,
    sourceTotalImageCount: 1450,
    suggestedAction: "same-name candidate",
    targetUnifiedCategory: "car",
    finalAction: "Merge",
  },
  {
    sourceCategoryId: "source-cat-cars",
    sourceCategory: "cars",
    sourcePath: "D:\\datasets\\coco_old",
    count: 112,
    sourceTotalImageCount: 1450,
    suggestedAction: "similar-name",
    targetUnifiedCategory: "car",
    finalAction: "Merge",
  },
  {
    sourceCategoryId: "source-cat-vehicle-car",
    sourceCategory: "vehicle_car",
    sourcePath: "D:\\datasets\\coco_old",
    count: 98,
    sourceTotalImageCount: 1450,
    suggestedAction: "similar-name",
    targetUnifiedCategory: "car",
    finalAction: "Merge",
  },
  {
    sourceCategoryId: "source-cat-background-obj",
    sourceCategory: "background_obj",
    sourcePath: "D:\\datasets\\coco_old",
    count: 31,
    sourceTotalImageCount: 1450,
    suggestedAction: "no match",
    finalAction: "Ignore",
  },
  {
    sourceCategoryId: "source-cat-pallet",
    sourceCategory: "pallet",
    sourcePath: "D:\\datasets\\coco_old",
    count: 207,
    sourceTotalImageCount: 1450,
    suggestedAction: "new",
    targetUnifiedCategory: "pallet",
    finalAction: "Create New",
  },
];

export const sampleBrowserPayload: BrowserPayload = {
  sources: sampleWorkspaceOverview.sources,
  categories: sampleWorkspaceOverview.categories,
  images: [
    {
      id: "img-001",
      filename: "frame_0001.jpg",
      sourceId: "source-coco-old",
      sourceName: "coco_old",
      originalPath: "D:\\datasets\\coco_old\\images\\frame_0001.jpg",
      annotationStatus: "annotated",
      imageHealthStatus: "healthy",
      imageHealthError: null,
      annotationCount: 3,
      maxBoxAreaRatio: 0.057,
      boxSummaries: [
        { categoryName: "screw", areaRatio: 0.057 },
        { categoryName: "nut", areaRatio: 0.031 },
        { categoryName: "nut", areaRatio: 0.019 },
      ],
      categoryIds: ["cat-screw", "cat-nut"],
      categories: ["screw", "nut"],
    },
    {
      id: "img-002",
      filename: "frame_0002.jpg",
      sourceId: "source-yolo-batch-2",
      sourceName: "yolo_batch_2",
      originalPath: "D:\\datasets\\yolo_batch_2\\images\\frame_0002.jpg",
      annotationStatus: "annotated",
      imageHealthStatus: "healthy",
      imageHealthError: null,
      annotationCount: 2,
      maxBoxAreaRatio: 0.084,
      boxSummaries: [
        { categoryName: "screw", areaRatio: 0.084 },
        { categoryName: "screw", areaRatio: 0.023 },
      ],
      categoryIds: ["cat-screw"],
      categories: ["screw"],
    },
    {
      id: "img-003",
      filename: "frame_0003.jpg",
      sourceId: "source-raw-2026-03",
      sourceName: "raw_2026_03",
      originalPath: "D:\\datasets\\raw_2026_03\\cameraA\\frame_0003.jpg",
      annotationStatus: "unannotated",
      imageHealthStatus: "healthy",
      imageHealthError: null,
      annotationCount: 0,
      maxBoxAreaRatio: null,
      boxSummaries: [],
      categoryIds: [],
      categories: [],
    },
    {
      id: "img-004",
      filename: "frame_0004.jpg",
      sourceId: "source-coco-old",
      sourceName: "coco_old",
      originalPath: "D:\\datasets\\coco_old\\images\\frame_0004.jpg",
      annotationStatus: "annotated",
      imageHealthStatus: "healthy",
      imageHealthError: null,
      annotationCount: 2,
      maxBoxAreaRatio: 0.241,
      boxSummaries: [
        { categoryName: "pallet", areaRatio: 0.241 },
        { categoryName: "pallet", areaRatio: 0.065 },
      ],
      categoryIds: ["cat-pallet"],
      categories: ["pallet"],
    },
    {
      id: "img-005",
      filename: "frame_0005.jpg",
      sourceId: "source-yolo-batch-2",
      sourceName: "yolo_batch_2",
      originalPath: "D:\\datasets\\yolo_batch_2\\images\\frame_0005.jpg",
      annotationStatus: "unannotated",
      imageHealthStatus: "healthy",
      imageHealthError: null,
      annotationCount: 0,
      maxBoxAreaRatio: null,
      boxSummaries: [],
      categoryIds: [],
      categories: [],
    },
    {
      id: "img-006",
      filename: "frame_0006.jpg",
      sourceId: "source-coco-old",
      sourceName: "coco_old",
      originalPath: "D:\\datasets\\coco_old\\images\\frame_0006.jpg",
      annotationStatus: "annotated",
      imageHealthStatus: "healthy",
      imageHealthError: null,
      annotationCount: 1,
      maxBoxAreaRatio: 0.036,
      boxSummaries: [
        { categoryName: "washer", areaRatio: 0.036 },
      ],
      categoryIds: ["cat-washer"],
      categories: ["washer"],
    },
  ],
};

export const sampleImageDetailPayload: ImageDetailPayload = {
  id: "img-001",
  filename: "frame_0001.jpg",
  sourceId: "source-coco-old",
  sourceName: "coco_old",
  originalPath: "D:\\datasets\\coco_old\\images\\frame_0001.jpg",
  annotationStatus: "annotated",
  imageHealthStatus: "healthy",
  imageHealthError: null,
  categories: ["screw", "nut"],
  width: 1280,
  height: 720,
  boxes: [
    {
      id: "box-001",
      categoryName: "screw",
      annotationFormat: "coco",
      bboxX: 180,
      bboxY: 140,
      bboxWidth: 240,
      bboxHeight: 220,
    },
    {
      id: "box-002",
      categoryName: "nut",
      annotationFormat: "coco",
      bboxX: 700,
      bboxY: 260,
      bboxWidth: 180,
      bboxHeight: 160,
    },
    {
      id: "box-008",
      categoryName: "nut",
      annotationFormat: "coco",
      bboxX: 930,
      bboxY: 118,
      bboxWidth: 132,
      bboxHeight: 132,
    },
  ],
};

export const sampleDatasetMapPayload: DatasetMapPayload = {
  workspaceId: "factory-defect-v1",
  scope: "object",
  modelId: "clip-vit-b32",
  models: [
    {
      id: "clip-vit-b32",
      family: "clip",
      displayName: "CLIP ViT-B/32",
      embeddingDim: 512,
      inputSize: 224,
      available: true,
      downloadRequired: false,
    },
    {
      id: "dinov2-small",
      family: "dinov2",
      displayName: "DINOv2 Small",
      embeddingDim: 384,
      inputSize: 224,
      available: true,
      downloadRequired: false,
    },
  ],
  runtime: {
    preference: "auto",
    selectedBackend: "cpu",
    capabilities: [
      {
        backend: "cuda",
        available: false,
        label: "CUDA",
        detail: "Unavailable in browser mock runtime.",
      },
      {
        backend: "windows-gpu",
        available: false,
        label: "Windows GPU",
        detail: "Unavailable in browser mock runtime.",
      },
      {
        backend: "cpu",
        available: true,
        label: "CPU",
        detail: "Browser mock runtime uses deterministic CPU sample data.",
      },
    ],
    fallbackReason: "GPU backends are unavailable in browser mock runtime.",
  },
  points: [
    {
      id: "map-point-box-001",
      scope: "object",
      imageId: "img-001",
      annotationId: "box-001",
      filename: "frame_0001.jpg",
      sourceId: "source-coco-old",
      sourceName: "coco_old",
      categoryId: "cat-screw",
      categoryName: "screw",
      bbox: { x: 180, y: 140, width: 240, height: 220, areaRatio: 0.057 },
      x: -0.72,
      y: 0.44,
      reviewStatus: "keep",
    },
    {
      id: "map-point-box-002",
      scope: "object",
      imageId: "img-001",
      annotationId: "box-002",
      filename: "frame_0001.jpg",
      sourceId: "source-coco-old",
      sourceName: "coco_old",
      categoryId: "cat-nut",
      categoryName: "nut",
      bbox: { x: 700, y: 260, width: 180, height: 160, areaRatio: 0.031 },
      x: -0.18,
      y: 0.61,
      reviewStatus: "needs-review",
    },
    {
      id: "map-point-box-003",
      scope: "object",
      imageId: "img-002",
      annotationId: "box-003",
      filename: "frame_0002.jpg",
      sourceId: "source-yolo-batch-2",
      sourceName: "yolo_batch_2",
      categoryId: "cat-screw",
      categoryName: "screw",
      bbox: { x: 410, y: 188, width: 210, height: 170, areaRatio: 0.084 },
      x: -0.66,
      y: 0.31,
      reviewStatus: "keep",
    },
    {
      id: "map-point-box-004",
      scope: "object",
      imageId: "img-004",
      annotationId: "box-004",
      filename: "frame_0004.jpg",
      sourceId: "source-coco-old",
      sourceName: "coco_old",
      categoryId: "cat-pallet",
      categoryName: "pallet",
      bbox: { x: 96, y: 220, width: 560, height: 310, areaRatio: 0.241 },
      x: 0.82,
      y: -0.36,
      reviewStatus: "fix",
    },
    {
      id: "map-point-box-005",
      scope: "object",
      imageId: "img-006",
      annotationId: "box-005",
      filename: "frame_0006.jpg",
      sourceId: "source-coco-old",
      sourceName: "coco_old",
      categoryId: "cat-washer",
      categoryName: "washer",
      bbox: { x: 540, y: 300, width: 120, height: 95, areaRatio: 0.036 },
      x: 0.24,
      y: -0.7,
      reviewStatus: "unreviewed",
    },
    {
      id: "map-point-box-006",
      scope: "object",
      imageId: "img-002",
      annotationId: "box-006",
      filename: "frame_0002.jpg",
      sourceId: "source-yolo-batch-2",
      sourceName: "yolo_batch_2",
      categoryId: "cat-screw",
      categoryName: "screw",
      bbox: { x: 760, y: 205, width: 96, height: 112, areaRatio: 0.023 },
      x: -0.51,
      y: 0.18,
      reviewStatus: "exclude",
    },
    {
      id: "map-point-box-007",
      scope: "object",
      imageId: "img-004",
      annotationId: "box-007",
      filename: "frame_0004.jpg",
      sourceId: "source-coco-old",
      sourceName: "coco_old",
      categoryId: "cat-pallet",
      categoryName: "pallet",
      bbox: { x: 690, y: 330, width: 260, height: 180, areaRatio: 0.065 },
      x: 0.71,
      y: -0.18,
      reviewStatus: "needs-review",
    },
    {
      id: "map-point-box-008",
      scope: "object",
      imageId: "img-001",
      annotationId: "box-008",
      filename: "frame_0001.jpg",
      sourceId: "source-coco-old",
      sourceName: "coco_old",
      categoryId: "cat-nut",
      categoryName: "nut",
      bbox: { x: 930, y: 118, width: 132, height: 132, areaRatio: 0.019 },
      x: -0.05,
      y: 0.53,
      reviewStatus: "fix",
    },
  ],
  jobs: [],
};

export const sampleCvatTasks: CvatTask[] = [
  {
    id: "cvat-task-001",
    name: "raw_2026_03_batch_01",
    imageCount: 120,
    status: "In Progress",
    projectName: "defect_v1",
    lastSyncAt: null,
    tempFolder: null,
  },
  {
    id: "cvat-task-002",
    name: "raw_2026_03_batch_02",
    imageCount: 80,
    status: "Ready Sync",
    projectName: "defect_v1",
    lastSyncAt: "2026-03-31 11:10",
    tempFolder: null,
  },
];

export const sampleAnnotationVersions: AnnotationVersion[] = [
  {
    id: "version-3",
    label: "v3",
    createdAt: "2026-03-31 11:25",
    sourceTask: "raw_2026_03_batch_02",
    imageCount: 80,
    boxCount: 412,
    notes: "sync from CVAT",
  },
  {
    id: "version-2",
    label: "v2",
    createdAt: "2026-03-31 10:55",
    sourceTask: "raw_2026_03_batch_01",
    imageCount: 120,
    boxCount: 618,
    notes: "sync from CVAT",
  },
  {
    id: "version-1",
    label: "v1",
    createdAt: "2026-03-31 10:20",
    sourceTask: "initial imported labels",
    imageCount: 2430,
    boxCount: 9184,
    notes: "initial normalized import",
  },
];

export const sampleExportHistory: ExportHistoryEntry[] = [
  {
    id: "export-1",
    outputFormat: "COCO",
    outputPath: "D:\\exports\\factory-defect-v1-coco-v2",
    createdAt: "2026-04-01T11:30:00Z",
    status: "completed",
    exportedImages: 1749,
    exportedBoxes: 14034,
  },
  {
    id: "export-2",
    outputFormat: "YOLO",
    outputPath: "D:\\exports\\factory-defect-v1-yolo",
    createdAt: "2026-04-01T11:42:00Z",
    status: "completed",
    exportedImages: 1749,
    exportedBoxes: 14034,
  },
];

export const sampleExportPreview: ExportPreview = {
  categoryCount: 3,
  includedImages: 1984,
  excludedImages: 231,
  includedBoxes: 8451,
  filenameConflicts: 4,
  conflictDetails: [
    {
      fileName: "0001.jpg",
      items: [
        {
          imageId: "img-1",
          sourceId: "source-a",
          originalPath: "D:\\datasets\\set-a\\0001.jpg",
        },
        {
          imageId: "img-2",
          sourceId: "source-b",
          originalPath: "D:\\datasets\\set-b\\0001.jpg",
        },
      ],
    },
  ],
  splitCounts: {
    train: 1388,
    valid: 298,
    test: 298,
  },
  outputPath: "D:\\exports\\factory-defect-v1-coco",
};
